value: ${BASE_URL}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
        github:
          client-id: ${GITHUB_CLIENT_ID}
          client-secret: ${GITHUB_CLIENT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${AWS_REGION_STATIC}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
jwt:
  secret: ${JWT_SECRET}
  cookie-secure: true
  redirect-url: ${REDIRECT_URL}
  redirect-url-failed: ${REDIRECT_URL_FAILED}
  token-validity-in-seconds: 86400
