spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: on

jwt:
  secret: ${JWT_SECRET}
  cookie-secure: true
  redirect-url: ${REDIRECT_URL}
  redirect-url-failed: ${REDIRECT_URL_FAILED}

aws:
  s3:
   access-key: ${AWS_ACCESS_KEY}
   secret-key: ${AWS_SECRET_KEY}
   bucket-name: ${AWS_S3_BUCKET}
   end-point: https://s3.ap-northeast-2.amazonaws.com
   region: ap-northeast-2



front-server:
  url: ${FRONT_SERVER_URL}

value: ${BASE_URL}
